# valine
valine_app_id: "xhxHWspVHrRE30VXrP2lRwKL-gzGzoHsz"
valine_app_key: "RkaItIEXBV9vOTBf3OYqnf9i"
valine_common_place_holder: "替换为一般占位符"
valine_micro_place_holder: "替换为微博客用占位符"

# footer, html code
footer: 
  - '<a href="{{ site.baseurl }}/static/xml/rss.xml">RSS</a> | '
  - '<a href="https://github.com/moi-mo/umaize">Theme UMaize</a>'
